#!/bin/bash

set -e

red=$(tput setaf 1)
green=$(tput setaf 2)
reset=$(tput sgr0)

overwrite(){
    # Move up and clear.
    printf "$(tput cuu $1)$(tput el)"
    printf "$2"
    # Move back down.
    printf "$(tput cud $1)"
}

printf "${red}foo${reset}\n"
printf "${green}bar${reset}\n"
sleep 1
overwrite 2 "FO\n"
